server:
  port: ${API_PORT:8080}

spring:
  application:
    api-prefix: ${API_PREFIX:/api/v1}
    name: vnpay
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL:http://localhost:8080/api/v1/payment/vn-pay-callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}